SECTION "Bank1", ROMX[$4000], BANK[1]
INCBIN "images/nearest/resources.bin", 0 * $4000, $4000

SECTION "Bank2", ROMX[$4000], BANK[2]
INCBIN "images/nearest/resources.bin", 1 * $4000, $4000

SECTION "Bank3", ROMX[$4000], BANK[3]
INCBIN "images/nearest/resources.bin", 2 * $4000, $4000

SECTION "Bank4", ROMX[$4000], BANK[4]
INCBIN "images/nearest/resources.bin", 3 * $4000, $4000

SECTION "Bank5", ROMX[$4000], BANK[5]
INCBIN "images/nearest/resources.bin", 4 * $4000, $4000

SECTION "Bank6", ROMX[$4000], BANK[6]
INCBIN "images/nearest/resources.bin", 5 * $4000, $4000

SECTION "Bank7", ROMX[$4000], BANK[7]
INCBIN "images/nearest/resources.bin", 6 * $4000, $4000

SECTION "Bank8", ROMX[$4000], BANK[8]
INCBIN "images/nearest/resources.bin", 7 * $4000, $4000

SECTION "Bank9", ROMX[$4000], BANK[9]
INCBIN "images/nearest/resources.bin", 8 * $4000, $4000

SECTION "Bank10", ROMX[$4000], BANK[10]
INCBIN "images/nearest/resources.bin", 9 * $4000, $4000

SECTION "Bank11", ROMX[$4000], BANK[11]
INCBIN "images/nearest/resources.bin", 10 * $4000, $4000

SECTION "Bank12", ROMX[$4000], BANK[12]
INCBIN "images/nearest/resources.bin", 11 * $4000, $4000

SECTION "Bank13", ROMX[$4000], BANK[13]
INCBIN "images/nearest/resources.bin", 12 * $4000, $4000

SECTION "Bank14", ROMX[$4000], BANK[14]
INCBIN "images/nearest/resources.bin", 13 * $4000, $4000

SECTION "Bank15", ROMX[$4000], BANK[15]
INCBIN "images/nearest/resources.bin", 14 * $4000, $4000

SECTION "Bank16", ROMX[$4000], BANK[16]
INCBIN "images/nearest/resources.bin", 15 * $4000, $4000

SECTION "Bank17", ROMX[$4000], BANK[17]
INCBIN "images/nearest/resources.bin", 16 * $4000, $4000

SECTION "Bank18", ROMX[$4000], BANK[18]
INCBIN "images/nearest/resources.bin", 17 * $4000, $4000

SECTION "Bank19", ROMX[$4000], BANK[19]
INCBIN "images/nearest/resources.bin", 18 * $4000, $4000

SECTION "Bank20", ROMX[$4000], BANK[20]
INCBIN "images/nearest/resources.bin", 19 * $4000, $4000

SECTION "Bank21", ROMX[$4000], BANK[21]
INCBIN "images/nearest/resources.bin", 20 * $4000, $4000

SECTION "Bank22", ROMX[$4000], BANK[22]
INCBIN "images/nearest/resources.bin", 21 * $4000, $4000

SECTION "Bank23", ROMX[$4000], BANK[23]
INCBIN "images/nearest/resources.bin", 22 * $4000, $4000

SECTION "Bank24", ROMX[$4000], BANK[24]
INCBIN "images/nearest/resources.bin", 23 * $4000, $4000

SECTION "Bank25", ROMX[$4000], BANK[25]
INCBIN "images/nearest/resources.bin", 24 * $4000, $4000

SECTION "Bank26", ROMX[$4000], BANK[26]
INCBIN "images/nearest/resources.bin", 25 * $4000, $4000

SECTION "Bank27", ROMX[$4000], BANK[27]
INCBIN "images/nearest/resources.bin", 26 * $4000, $4000

SECTION "Bank28", ROMX[$4000], BANK[28]
INCBIN "images/nearest/resources.bin", 27 * $4000, $4000

SECTION "Bank29", ROMX[$4000], BANK[29]
INCBIN "images/nearest/resources.bin", 28 * $4000, $4000

SECTION "Bank30", ROMX[$4000], BANK[30]
INCBIN "images/nearest/resources.bin", 29 * $4000, $4000

SECTION "Bank31", ROMX[$4000], BANK[31]
INCBIN "images/nearest/resources.bin", 30 * $4000, $4000

SECTION "Bank32", ROMX[$4000], BANK[32]
INCBIN "images/nearest/resources.bin", 31 * $4000, $4000

SECTION "Bank33", ROMX[$4000], BANK[33]
INCBIN "images/nearest/resources.bin", 32 * $4000, $4000

SECTION "Bank34", ROMX[$4000], BANK[34]
INCBIN "images/nearest/resources.bin", 33 * $4000, $4000

SECTION "Bank35", ROMX[$4000], BANK[35]
INCBIN "images/nearest/resources.bin", 34 * $4000, $4000

SECTION "Bank36", ROMX[$4000], BANK[36]
INCBIN "images/nearest/resources.bin", 35 * $4000, $4000

SECTION "Bank37", ROMX[$4000], BANK[37]
INCBIN "images/nearest/resources.bin", 36 * $4000, $4000

SECTION "Bank38", ROMX[$4000], BANK[38]
INCBIN "images/nearest/resources.bin", 37 * $4000, $4000

SECTION "Bank39", ROMX[$4000], BANK[39]
INCBIN "images/nearest/resources.bin", 38 * $4000, $4000

SECTION "Bank40", ROMX[$4000], BANK[40]
INCBIN "images/nearest/resources.bin", 39 * $4000, $4000

SECTION "Bank41", ROMX[$4000], BANK[41]
INCBIN "images/nearest/resources.bin", 40 * $4000, $4000

SECTION "Bank42", ROMX[$4000], BANK[42]
INCBIN "images/nearest/resources.bin", 41 * $4000, $4000

SECTION "Bank43", ROMX[$4000], BANK[43]
INCBIN "images/nearest/resources.bin", 42 * $4000, $4000

SECTION "Bank44", ROMX[$4000], BANK[44]
INCBIN "images/nearest/resources.bin", 43 * $4000, $4000

SECTION "Bank45", ROMX[$4000], BANK[45]
INCBIN "images/nearest/resources.bin", 44 * $4000, $4000

SECTION "Bank46", ROMX[$4000], BANK[46]
INCBIN "images/nearest/resources.bin", 45 * $4000, $4000

SECTION "Bank47", ROMX[$4000], BANK[47]
INCBIN "images/nearest/resources.bin", 46 * $4000, $4000

SECTION "Bank48", ROMX[$4000], BANK[48]
INCBIN "images/nearest/resources.bin", 47 * $4000, $4000

SECTION "Bank49", ROMX[$4000], BANK[49]
INCBIN "images/nearest/resources.bin", 48 * $4000, $4000

SECTION "Bank50", ROMX[$4000], BANK[50]
INCBIN "images/nearest/resources.bin", 49 * $4000, $4000

SECTION "Bank51", ROMX[$4000], BANK[51]
INCBIN "images/nearest/resources.bin", 50 * $4000, $4000

SECTION "Bank52", ROMX[$4000], BANK[52]
INCBIN "images/nearest/resources.bin", 51 * $4000, $4000

SECTION "Bank53", ROMX[$4000], BANK[53]
INCBIN "images/nearest/resources.bin", 52 * $4000, $4000

SECTION "Bank54", ROMX[$4000], BANK[54]
INCBIN "images/nearest/resources.bin", 53 * $4000, $4000

SECTION "Bank55", ROMX[$4000], BANK[55]
INCBIN "images/nearest/resources.bin", 54 * $4000, $4000

SECTION "Bank56", ROMX[$4000], BANK[56]
INCBIN "images/nearest/resources.bin", 55 * $4000, $4000

SECTION "Bank57", ROMX[$4000], BANK[57]
INCBIN "images/nearest/resources.bin", 56 * $4000, $4000

SECTION "Bank58", ROMX[$4000], BANK[58]
INCBIN "images/nearest/resources.bin", 57 * $4000, $4000

SECTION "Bank59", ROMX[$4000], BANK[59]
INCBIN "images/nearest/resources.bin", 58 * $4000, $4000

SECTION "Bank60", ROMX[$4000], BANK[60]
INCBIN "images/nearest/resources.bin", 59 * $4000, $4000

SECTION "Bank61", ROMX[$4000], BANK[61]
INCBIN "images/nearest/resources.bin", 60 * $4000, $4000

SECTION "Bank62", ROMX[$4000], BANK[62]
INCBIN "images/nearest/resources.bin", 61 * $4000, $4000

SECTION "Bank63", ROMX[$4000], BANK[63]
INCBIN "images/nearest/resources.bin", 62 * $4000, $4000

SECTION "Bank64", ROMX[$4000], BANK[64]
INCBIN "images/nearest/resources.bin", 63 * $4000, $4000

SECTION "Bank65", ROMX[$4000], BANK[65]
INCBIN "images/nearest/resources.bin", 64 * $4000, $4000

SECTION "Bank66", ROMX[$4000], BANK[66]
INCBIN "images/nearest/resources.bin", 65 * $4000, $4000

SECTION "Bank67", ROMX[$4000], BANK[67]
INCBIN "images/nearest/resources.bin", 66 * $4000, $4000

SECTION "Bank68", ROMX[$4000], BANK[68]
INCBIN "images/nearest/resources.bin", 67 * $4000, $4000

SECTION "Bank69", ROMX[$4000], BANK[69]
INCBIN "images/nearest/resources.bin", 68 * $4000, $4000

SECTION "Bank70", ROMX[$4000], BANK[70]
INCBIN "images/nearest/resources.bin", 69 * $4000, $4000

SECTION "Bank71", ROMX[$4000], BANK[71]
INCBIN "images/nearest/resources.bin", 70 * $4000, $4000

SECTION "Bank72", ROMX[$4000], BANK[72]
INCBIN "images/nearest/resources.bin", 71 * $4000, $4000

SECTION "Bank73", ROMX[$4000], BANK[73]
INCBIN "images/nearest/resources.bin", 72 * $4000, $4000

SECTION "Bank74", ROMX[$4000], BANK[74]
INCBIN "images/nearest/resources.bin", 73 * $4000, $4000

SECTION "Bank75", ROMX[$4000], BANK[75]
INCBIN "images/nearest/resources.bin", 74 * $4000, $4000

SECTION "Bank76", ROMX[$4000], BANK[76]
INCBIN "images/nearest/resources.bin", 75 * $4000, $4000

SECTION "Bank77", ROMX[$4000], BANK[77]
INCBIN "images/nearest/resources.bin", 76 * $4000, $4000

SECTION "Bank78", ROMX[$4000], BANK[78]
INCBIN "images/nearest/resources.bin", 77 * $4000, $4000

SECTION "Bank79", ROMX[$4000], BANK[79]
INCBIN "images/nearest/resources.bin", 78 * $4000, $4000

SECTION "Bank80", ROMX[$4000], BANK[80]
INCBIN "images/nearest/resources.bin", 79 * $4000, $4000

SECTION "Bank81", ROMX[$4000], BANK[81]
INCBIN "images/nearest/resources.bin", 80 * $4000, $4000

SECTION "Bank82", ROMX[$4000], BANK[82]
INCBIN "images/nearest/resources.bin", 81 * $4000, $4000

SECTION "Bank83", ROMX[$4000], BANK[83]
INCBIN "images/nearest/resources.bin", 82 * $4000, $4000

SECTION "Bank84", ROMX[$4000], BANK[84]
INCBIN "images/nearest/resources.bin", 83 * $4000, $4000

SECTION "Bank85", ROMX[$4000], BANK[85]
INCBIN "images/nearest/resources.bin", 84 * $4000, $4000

SECTION "Bank86", ROMX[$4000], BANK[86]
INCBIN "images/nearest/resources.bin", 85 * $4000, $4000

SECTION "Bank87", ROMX[$4000], BANK[87]
INCBIN "images/nearest/resources.bin", 86 * $4000, $4000

SECTION "Bank88", ROMX[$4000], BANK[88]
INCBIN "images/nearest/resources.bin", 87 * $4000, $4000

SECTION "Bank89", ROMX[$4000], BANK[89]
INCBIN "images/nearest/resources.bin", 88 * $4000, $4000

SECTION "Bank90", ROMX[$4000], BANK[90]
INCBIN "images/nearest/resources.bin", 89 * $4000, $4000

SECTION "Bank91", ROMX[$4000], BANK[91]
INCBIN "images/nearest/resources.bin", 90 * $4000, $4000

SECTION "Bank92", ROMX[$4000], BANK[92]
INCBIN "images/nearest/resources.bin", 91 * $4000, $4000

SECTION "Bank93", ROMX[$4000], BANK[93]
INCBIN "images/nearest/resources.bin", 92 * $4000, $4000

SECTION "Bank94", ROMX[$4000], BANK[94]
INCBIN "images/nearest/resources.bin", 93 * $4000, $4000

SECTION "Bank95", ROMX[$4000], BANK[95]
INCBIN "images/nearest/resources.bin", 94 * $4000, $4000

SECTION "Bank96", ROMX[$4000], BANK[96]
INCBIN "images/nearest/resources.bin", 95 * $4000, $4000

SECTION "Bank97", ROMX[$4000], BANK[97]
INCBIN "images/nearest/resources.bin", 96 * $4000, $4000

SECTION "Bank98", ROMX[$4000], BANK[98]
INCBIN "images/nearest/resources.bin", 97 * $4000, $4000

SECTION "Bank99", ROMX[$4000], BANK[99]
INCBIN "images/nearest/resources.bin", 98 * $4000, $4000

SECTION "Bank100", ROMX[$4000], BANK[100]
INCBIN "images/nearest/resources.bin", 99 * $4000, $4000

SECTION "Bank101", ROMX[$4000], BANK[101]
INCBIN "images/nearest/resources.bin", 100 * $4000, $4000

SECTION "Bank102", ROMX[$4000], BANK[102]
INCBIN "images/nearest/resources.bin", 101 * $4000, $4000

SECTION "Bank103", ROMX[$4000], BANK[103]
INCBIN "images/nearest/resources.bin", 102 * $4000, $4000

SECTION "Bank104", ROMX[$4000], BANK[104]
INCBIN "images/nearest/resources.bin", 103 * $4000, $4000

SECTION "Bank105", ROMX[$4000], BANK[105]
INCBIN "images/nearest/resources.bin", 104 * $4000, $4000

SECTION "Bank106", ROMX[$4000], BANK[106]
INCBIN "images/nearest/resources.bin", 105 * $4000, $4000

SECTION "Bank107", ROMX[$4000], BANK[107]
INCBIN "images/nearest/resources.bin", 106 * $4000, $4000

SECTION "Bank108", ROMX[$4000], BANK[108]
INCBIN "images/nearest/resources.bin", 107 * $4000, $4000

SECTION "Bank109", ROMX[$4000], BANK[109]
INCBIN "images/nearest/resources.bin", 108 * $4000, $4000

SECTION "Bank110", ROMX[$4000], BANK[110]
INCBIN "images/nearest/resources.bin", 109 * $4000, $4000

SECTION "Bank111", ROMX[$4000], BANK[111]
INCBIN "images/nearest/resources.bin", 110 * $4000, $4000

SECTION "Bank112", ROMX[$4000], BANK[112]
INCBIN "images/nearest/resources.bin", 111 * $4000, $4000

SECTION "Bank113", ROMX[$4000], BANK[113]
INCBIN "images/nearest/resources.bin", 112 * $4000, $4000

SECTION "Bank114", ROMX[$4000], BANK[114]
INCBIN "images/nearest/resources.bin", 113 * $4000, $4000

SECTION "Bank115", ROMX[$4000], BANK[115]
INCBIN "images/nearest/resources.bin", 114 * $4000, $4000

SECTION "Bank116", ROMX[$4000], BANK[116]
INCBIN "images/nearest/resources.bin", 115 * $4000, $4000

SECTION "Bank117", ROMX[$4000], BANK[117]
INCBIN "images/nearest/resources.bin", 116 * $4000, $4000

SECTION "Bank118", ROMX[$4000], BANK[118]
INCBIN "images/nearest/resources.bin", 117 * $4000, $4000

SECTION "Bank119", ROMX[$4000], BANK[119]
INCBIN "images/nearest/resources.bin", 118 * $4000, $4000

SECTION "Bank120", ROMX[$4000], BANK[120]
INCBIN "images/nearest/resources.bin", 119 * $4000, $4000

SECTION "Bank121", ROMX[$4000], BANK[121]
INCBIN "images/nearest/resources.bin", 120 * $4000, $4000

SECTION "Bank122", ROMX[$4000], BANK[122]
INCBIN "images/nearest/resources.bin", 121 * $4000, $4000

SECTION "Bank123", ROMX[$4000], BANK[123]
INCBIN "images/nearest/resources.bin", 122 * $4000, $4000

SECTION "Bank124", ROMX[$4000], BANK[124]
INCBIN "images/nearest/resources.bin", 123 * $4000, $4000

SECTION "Bank125", ROMX[$4000], BANK[125]
INCBIN "images/nearest/resources.bin", 124 * $4000, $4000

SECTION "Bank126", ROMX[$4000], BANK[126]
INCBIN "images/nearest/resources.bin", 125 * $4000, $4000

SECTION "Bank127", ROMX[$4000], BANK[127]
INCBIN "images/nearest/resources.bin", 126 * $4000, $4000

SECTION "Bank128", ROMX[$4000], BANK[128]
INCBIN "images/nearest/resources.bin", 127 * $4000, $4000

SECTION "Bank129", ROMX[$4000], BANK[129]
INCBIN "images/nearest/resources.bin", 128 * $4000, $4000

SECTION "Bank130", ROMX[$4000], BANK[130]
INCBIN "images/nearest/resources.bin", 129 * $4000, $4000

SECTION "Bank131", ROMX[$4000], BANK[131]
INCBIN "images/nearest/resources.bin", 130 * $4000, $4000

SECTION "Bank132", ROMX[$4000], BANK[132]
INCBIN "images/nearest/resources.bin", 131 * $4000, $4000

SECTION "Bank133", ROMX[$4000], BANK[133]
INCBIN "images/nearest/resources.bin", 132 * $4000, $4000

SECTION "Bank134", ROMX[$4000], BANK[134]
INCBIN "images/nearest/resources.bin", 133 * $4000, $4000

SECTION "Bank135", ROMX[$4000], BANK[135]
INCBIN "images/nearest/resources.bin", 134 * $4000, $4000

SECTION "Bank136", ROMX[$4000], BANK[136]
INCBIN "images/nearest/resources.bin", 135 * $4000, $4000

SECTION "Bank137", ROMX[$4000], BANK[137]
INCBIN "images/nearest/resources.bin", 136 * $4000, $4000

SECTION "Bank138", ROMX[$4000], BANK[138]
INCBIN "images/nearest/resources.bin", 137 * $4000, $4000

SECTION "Bank139", ROMX[$4000], BANK[139]
INCBIN "images/nearest/resources.bin", 138 * $4000, $4000

SECTION "Bank140", ROMX[$4000], BANK[140]
INCBIN "images/nearest/resources.bin", 139 * $4000, $4000

SECTION "Bank141", ROMX[$4000], BANK[141]
INCBIN "images/nearest/resources.bin", 140 * $4000, $4000

SECTION "Bank142", ROMX[$4000], BANK[142]
INCBIN "images/nearest/resources.bin", 141 * $4000, $4000

SECTION "Bank143", ROMX[$4000], BANK[143]
INCBIN "images/nearest/resources.bin", 142 * $4000, $4000

SECTION "Bank144", ROMX[$4000], BANK[144]
INCBIN "images/nearest/resources.bin", 143 * $4000, $4000

SECTION "Bank145", ROMX[$4000], BANK[145]
INCBIN "images/nearest/resources.bin", 144 * $4000, $4000

SECTION "Bank146", ROMX[$4000], BANK[146]
INCBIN "images/nearest/resources.bin", 145 * $4000, $4000

SECTION "Bank147", ROMX[$4000], BANK[147]
INCBIN "images/nearest/resources.bin", 146 * $4000, $4000

SECTION "Bank148", ROMX[$4000], BANK[148]
INCBIN "images/nearest/resources.bin", 147 * $4000, $4000

SECTION "Bank149", ROMX[$4000], BANK[149]
INCBIN "images/nearest/resources.bin", 148 * $4000, $4000

SECTION "Bank150", ROMX[$4000], BANK[150]
INCBIN "images/nearest/resources.bin", 149 * $4000, $4000

SECTION "Bank151", ROMX[$4000], BANK[151]
INCBIN "images/nearest/resources.bin", 150 * $4000, $4000

SECTION "Bank152", ROMX[$4000], BANK[152]
INCBIN "images/nearest/resources.bin", 151 * $4000, $4000

SECTION "Bank153", ROMX[$4000], BANK[153]
INCBIN "images/nearest/resources.bin", 152 * $4000, $4000

SECTION "Bank154", ROMX[$4000], BANK[154]
INCBIN "images/nearest/resources.bin", 153 * $4000, $4000

SECTION "Bank155", ROMX[$4000], BANK[155]
INCBIN "images/nearest/resources.bin", 154 * $4000, $4000

SECTION "Bank156", ROMX[$4000], BANK[156]
INCBIN "images/nearest/resources.bin", 155 * $4000, $4000

SECTION "Bank157", ROMX[$4000], BANK[157]
INCBIN "images/nearest/resources.bin", 156 * $4000, $4000

SECTION "Bank158", ROMX[$4000], BANK[158]
INCBIN "images/nearest/resources.bin", 157 * $4000, $4000

SECTION "Bank159", ROMX[$4000], BANK[159]
INCBIN "images/nearest/resources.bin", 158 * $4000, $4000

SECTION "Bank160", ROMX[$4000], BANK[160]
INCBIN "images/nearest/resources.bin", 159 * $4000, $4000

SECTION "Bank161", ROMX[$4000], BANK[161]
INCBIN "images/nearest/resources.bin", 160 * $4000, $4000

SECTION "Bank162", ROMX[$4000], BANK[162]
INCBIN "images/nearest/resources.bin", 161 * $4000, $4000

SECTION "Bank163", ROMX[$4000], BANK[163]
INCBIN "images/nearest/resources.bin", 162 * $4000, $4000

SECTION "Bank164", ROMX[$4000], BANK[164]
INCBIN "images/nearest/resources.bin", 163 * $4000, $4000

SECTION "Bank165", ROMX[$4000], BANK[165]
INCBIN "images/nearest/resources.bin", 164 * $4000, $4000

SECTION "Bank166", ROMX[$4000], BANK[166]
INCBIN "images/nearest/resources.bin", 165 * $4000, $4000

SECTION "Bank167", ROMX[$4000], BANK[167]
INCBIN "images/nearest/resources.bin", 166 * $4000, $4000

SECTION "Bank168", ROMX[$4000], BANK[168]
INCBIN "images/nearest/resources.bin", 167 * $4000, $4000

SECTION "Bank169", ROMX[$4000], BANK[169]
INCBIN "images/nearest/resources.bin", 168 * $4000, $4000

SECTION "Bank170", ROMX[$4000], BANK[170]
INCBIN "images/nearest/resources.bin", 169 * $4000, $4000

SECTION "Bank171", ROMX[$4000], BANK[171]
INCBIN "images/nearest/resources.bin", 170 * $4000, $4000

SECTION "Bank172", ROMX[$4000], BANK[172]
INCBIN "images/nearest/resources.bin", 171 * $4000, $4000

SECTION "Bank173", ROMX[$4000], BANK[173]
INCBIN "images/nearest/resources.bin", 172 * $4000, $4000

SECTION "Bank174", ROMX[$4000], BANK[174]
INCBIN "images/nearest/resources.bin", 173 * $4000, $4000

SECTION "Bank175", ROMX[$4000], BANK[175]
INCBIN "images/nearest/resources.bin", 174 * $4000, $4000

SECTION "Bank176", ROMX[$4000], BANK[176]
INCBIN "images/nearest/resources.bin", 175 * $4000, $4000

SECTION "Bank177", ROMX[$4000], BANK[177]
INCBIN "images/nearest/resources.bin", 176 * $4000, $4000

SECTION "Bank178", ROMX[$4000], BANK[178]
INCBIN "images/nearest/resources.bin", 177 * $4000, $4000

SECTION "Bank179", ROMX[$4000], BANK[179]
INCBIN "images/nearest/resources.bin", 178 * $4000, $4000

SECTION "Bank180", ROMX[$4000], BANK[180]
INCBIN "images/nearest/resources.bin", 179 * $4000, $4000

SECTION "Bank181", ROMX[$4000], BANK[181]
INCBIN "images/nearest/resources.bin", 180 * $4000, $4000

SECTION "Bank182", ROMX[$4000], BANK[182]
INCBIN "images/nearest/resources.bin", 181 * $4000, $4000

SECTION "Bank183", ROMX[$4000], BANK[183]
INCBIN "images/nearest/resources.bin", 182 * $4000, $4000

SECTION "Bank184", ROMX[$4000], BANK[184]
INCBIN "images/nearest/resources.bin", 183 * $4000, $4000

SECTION "Bank185", ROMX[$4000], BANK[185]
INCBIN "images/nearest/resources.bin", 184 * $4000, $4000

SECTION "Bank186", ROMX[$4000], BANK[186]
INCBIN "images/nearest/resources.bin", 185 * $4000, $4000

SECTION "Bank187", ROMX[$4000], BANK[187]
INCBIN "images/nearest/resources.bin", 186 * $4000, $4000

SECTION "Bank188", ROMX[$4000], BANK[188]
INCBIN "images/nearest/resources.bin", 187 * $4000, $4000

SECTION "Bank189", ROMX[$4000], BANK[189]
INCBIN "images/nearest/resources.bin", 188 * $4000, $4000

SECTION "Bank190", ROMX[$4000], BANK[190]
INCBIN "images/nearest/resources.bin", 189 * $4000, $4000

SECTION "Bank191", ROMX[$4000], BANK[191]
INCBIN "images/nearest/resources.bin", 190 * $4000, $4000

SECTION "Bank192", ROMX[$4000], BANK[192]
INCBIN "images/nearest/resources.bin", 191 * $4000, $4000

SECTION "Bank193", ROMX[$4000], BANK[193]
INCBIN "images/nearest/resources.bin", 192 * $4000, $4000

SECTION "Bank194", ROMX[$4000], BANK[194]
INCBIN "images/nearest/resources.bin", 193 * $4000, $4000

SECTION "Bank195", ROMX[$4000], BANK[195]
INCBIN "images/nearest/resources.bin", 194 * $4000, $4000

SECTION "Bank196", ROMX[$4000], BANK[196]
INCBIN "images/nearest/resources.bin", 195 * $4000, $4000

SECTION "Bank197", ROMX[$4000], BANK[197]
INCBIN "images/nearest/resources.bin", 196 * $4000, $4000

SECTION "Bank198", ROMX[$4000], BANK[198]
INCBIN "images/nearest/resources.bin", 197 * $4000, $4000

SECTION "Bank199", ROMX[$4000], BANK[199]
INCBIN "images/nearest/resources.bin", 198 * $4000, $4000

SECTION "Bank200", ROMX[$4000], BANK[200]
INCBIN "images/nearest/resources.bin", 199 * $4000, $4000

SECTION "Bank201", ROMX[$4000], BANK[201]
INCBIN "images/nearest/resources.bin", 200 * $4000, $4000

SECTION "Bank202", ROMX[$4000], BANK[202]
INCBIN "images/nearest/resources.bin", 201 * $4000, $4000

SECTION "Bank203", ROMX[$4000], BANK[203]
INCBIN "images/nearest/resources.bin", 202 * $4000, $4000

SECTION "Bank204", ROMX[$4000], BANK[204]
INCBIN "images/nearest/resources.bin", 203 * $4000, $4000

SECTION "Bank205", ROMX[$4000], BANK[205]
INCBIN "images/nearest/resources.bin", 204 * $4000, $4000

SECTION "Bank206", ROMX[$4000], BANK[206]
INCBIN "images/nearest/resources.bin", 205 * $4000, $4000

SECTION "Bank207", ROMX[$4000], BANK[207]
INCBIN "images/nearest/resources.bin", 206 * $4000, $4000

SECTION "Bank208", ROMX[$4000], BANK[208]
INCBIN "images/nearest/resources.bin", 207 * $4000, $4000

SECTION "Bank209", ROMX[$4000], BANK[209]
INCBIN "images/nearest/resources.bin", 208 * $4000, $4000

SECTION "Bank210", ROMX[$4000], BANK[210]
INCBIN "images/nearest/resources.bin", 209 * $4000, $4000

SECTION "Bank211", ROMX[$4000], BANK[211]
INCBIN "images/nearest/resources.bin", 210 * $4000, $4000

SECTION "Bank212", ROMX[$4000], BANK[212]
INCBIN "images/nearest/resources.bin", 211 * $4000, $4000

SECTION "Bank213", ROMX[$4000], BANK[213]
INCBIN "images/nearest/resources.bin", 212 * $4000, $4000

SECTION "Bank214", ROMX[$4000], BANK[214]
INCBIN "images/nearest/resources.bin", 213 * $4000, $4000

SECTION "Bank215", ROMX[$4000], BANK[215]
INCBIN "images/nearest/resources.bin", 214 * $4000, $4000

SECTION "Bank216", ROMX[$4000], BANK[216]
INCBIN "images/nearest/resources.bin", 215 * $4000, $4000

SECTION "Bank217", ROMX[$4000], BANK[217]
INCBIN "images/nearest/resources.bin", 216 * $4000, $4000

SECTION "Bank218", ROMX[$4000], BANK[218]
INCBIN "images/nearest/resources.bin", 217 * $4000, $4000

SECTION "Bank219", ROMX[$4000], BANK[219]
INCBIN "images/nearest/resources.bin", 218 * $4000, $4000

SECTION "Bank220", ROMX[$4000], BANK[220]
INCBIN "images/nearest/resources.bin", 219 * $4000, $4000

SECTION "Bank221", ROMX[$4000], BANK[221]
INCBIN "images/nearest/resources.bin", 220 * $4000, $4000

SECTION "Bank222", ROMX[$4000], BANK[222]
INCBIN "images/nearest/resources.bin", 221 * $4000, $4000

SECTION "Bank223", ROMX[$4000], BANK[223]
INCBIN "images/nearest/resources.bin", 222 * $4000, $4000

SECTION "Bank224", ROMX[$4000], BANK[224]
INCBIN "images/nearest/resources.bin", 223 * $4000, $4000

SECTION "Bank225", ROMX[$4000], BANK[225]
INCBIN "images/nearest/resources.bin", 224 * $4000, $4000

SECTION "Bank226", ROMX[$4000], BANK[226]
INCBIN "images/nearest/resources.bin", 225 * $4000, $4000

SECTION "Bank227", ROMX[$4000], BANK[227]
INCBIN "images/nearest/resources.bin", 226 * $4000, $4000

SECTION "Bank228", ROMX[$4000], BANK[228]
INCBIN "images/nearest/resources.bin", 227 * $4000, $4000

SECTION "Bank229", ROMX[$4000], BANK[229]
INCBIN "images/nearest/resources.bin", 228 * $4000, $4000

SECTION "Bank230", ROMX[$4000], BANK[230]
INCBIN "images/nearest/resources.bin", 229 * $4000, $4000

SECTION "Bank231", ROMX[$4000], BANK[231]
INCBIN "images/nearest/resources.bin", 230 * $4000, $4000

SECTION "Bank232", ROMX[$4000], BANK[232]
INCBIN "images/nearest/resources.bin", 231 * $4000, $4000

SECTION "Bank233", ROMX[$4000], BANK[233]
INCBIN "images/nearest/resources.bin", 232 * $4000, $4000

SECTION "Bank234", ROMX[$4000], BANK[234]
INCBIN "images/nearest/resources.bin", 233 * $4000, $4000

SECTION "Bank235", ROMX[$4000], BANK[235]
INCBIN "images/nearest/resources.bin", 234 * $4000, $4000

SECTION "Bank236", ROMX[$4000], BANK[236]
INCBIN "images/nearest/resources.bin", 235 * $4000, $4000

SECTION "Bank237", ROMX[$4000], BANK[237]
INCBIN "images/nearest/resources.bin", 236 * $4000, $4000

SECTION "Bank238", ROMX[$4000], BANK[238]
INCBIN "images/nearest/resources.bin", 237 * $4000, $4000

SECTION "Bank239", ROMX[$4000], BANK[239]
INCBIN "images/nearest/resources.bin", 238 * $4000, $4000

SECTION "Bank240", ROMX[$4000], BANK[240]
INCBIN "images/nearest/resources.bin", 239 * $4000, $4000

SECTION "Bank241", ROMX[$4000], BANK[241]
INCBIN "images/nearest/resources.bin", 240 * $4000, $4000

SECTION "Bank242", ROMX[$4000], BANK[242]
INCBIN "images/nearest/resources.bin", 241 * $4000, $4000

SECTION "Bank243", ROMX[$4000], BANK[243]
INCBIN "images/nearest/resources.bin", 242 * $4000, $4000

SECTION "Bank244", ROMX[$4000], BANK[244]
INCBIN "images/nearest/resources.bin", 243 * $4000, $4000

SECTION "Bank245", ROMX[$4000], BANK[245]
INCBIN "images/nearest/resources.bin", 244 * $4000, $4000

SECTION "Bank246", ROMX[$4000], BANK[246]
INCBIN "images/nearest/resources.bin", 245 * $4000, $4000

SECTION "Bank247", ROMX[$4000], BANK[247]
INCBIN "images/nearest/resources.bin", 246 * $4000, $4000

SECTION "Bank248", ROMX[$4000], BANK[248]
INCBIN "images/nearest/resources.bin", 247 * $4000, $4000

SECTION "Bank249", ROMX[$4000], BANK[249]
INCBIN "images/nearest/resources.bin", 248 * $4000, $4000

SECTION "Bank250", ROMX[$4000], BANK[250]
INCBIN "images/nearest/resources.bin", 249 * $4000, $4000

SECTION "Bank251", ROMX[$4000], BANK[251]
INCBIN "images/nearest/resources.bin", 250 * $4000, $4000

SECTION "Bank252", ROMX[$4000], BANK[252]
INCBIN "images/nearest/resources.bin", 251 * $4000, $4000

SECTION "Bank253", ROMX[$4000], BANK[253]
INCBIN "images/nearest/resources.bin", 252 * $4000, $4000

SECTION "Bank254", ROMX[$4000], BANK[254]
INCBIN "images/nearest/resources.bin", 253 * $4000, $4000

SECTION "Bank255", ROMX[$4000], BANK[255]
INCBIN "images/nearest/resources.bin", 254 * $4000, $4000

SECTION "Bank256", ROMX[$4000], BANK[256]
INCBIN "images/nearest/resources.bin", 255 * $4000, $4000

SECTION "Bank257", ROMX[$4000], BANK[257]
INCBIN "images/nearest/resources.bin", 256 * $4000, $4000

SECTION "Bank258", ROMX[$4000], BANK[258]
INCBIN "images/nearest/resources.bin", 257 * $4000, $4000

SECTION "Bank259", ROMX[$4000], BANK[259]
INCBIN "images/nearest/resources.bin", 258 * $4000, $4000

SECTION "Bank260", ROMX[$4000], BANK[260]
INCBIN "images/nearest/resources.bin", 259 * $4000, $4000

SECTION "Bank261", ROMX[$4000], BANK[261]
INCBIN "images/nearest/resources.bin", 260 * $4000, $4000

SECTION "Bank262", ROMX[$4000], BANK[262]
INCBIN "images/nearest/resources.bin", 261 * $4000, $4000

SECTION "Bank263", ROMX[$4000], BANK[263]
INCBIN "images/nearest/resources.bin", 262 * $4000, $4000

SECTION "Bank264", ROMX[$4000], BANK[264]
INCBIN "images/nearest/resources.bin", 263 * $4000, $4000

SECTION "Bank265", ROMX[$4000], BANK[265]
INCBIN "images/nearest/resources.bin", 264 * $4000, $4000

SECTION "Bank266", ROMX[$4000], BANK[266]
INCBIN "images/nearest/resources.bin", 265 * $4000, $4000

SECTION "Bank267", ROMX[$4000], BANK[267]
INCBIN "images/nearest/resources.bin", 266 * $4000, $4000

SECTION "Bank268", ROMX[$4000], BANK[268]
INCBIN "images/nearest/resources.bin", 267 * $4000, $4000

SECTION "Bank269", ROMX[$4000], BANK[269]
INCBIN "images/nearest/resources.bin", 268 * $4000, $4000

SECTION "Bank270", ROMX[$4000], BANK[270]
INCBIN "images/nearest/resources.bin", 269 * $4000, $4000

SECTION "Bank271", ROMX[$4000], BANK[271]
INCBIN "images/nearest/resources.bin", 270 * $4000, $4000

SECTION "Bank272", ROMX[$4000], BANK[272]
INCBIN "images/nearest/resources.bin", 271 * $4000, $4000

SECTION "Bank273", ROMX[$4000], BANK[273]
INCBIN "images/nearest/resources.bin", 272 * $4000, $4000

SECTION "Bank274", ROMX[$4000], BANK[274]
INCBIN "images/nearest/resources.bin", 273 * $4000, $4000

SECTION "Bank275", ROMX[$4000], BANK[275]
INCBIN "images/nearest/resources.bin", 274 * $4000, $4000

SECTION "Bank276", ROMX[$4000], BANK[276]
INCBIN "images/nearest/resources.bin", 275 * $4000, $4000

SECTION "Bank277", ROMX[$4000], BANK[277]
INCBIN "images/nearest/resources.bin", 276 * $4000, $4000

SECTION "Bank278", ROMX[$4000], BANK[278]
INCBIN "images/nearest/resources.bin", 277 * $4000, $4000

SECTION "Bank279", ROMX[$4000], BANK[279]
INCBIN "images/nearest/resources.bin", 278 * $4000, $4000

SECTION "Bank280", ROMX[$4000], BANK[280]
INCBIN "images/nearest/resources.bin", 279 * $4000, $4000

SECTION "Bank281", ROMX[$4000], BANK[281]
INCBIN "images/nearest/resources.bin", 280 * $4000, $4000

SECTION "Bank282", ROMX[$4000], BANK[282]
INCBIN "images/nearest/resources.bin", 281 * $4000, $4000

SECTION "Bank283", ROMX[$4000], BANK[283]
INCBIN "images/nearest/resources.bin", 282 * $4000, $4000

SECTION "Bank284", ROMX[$4000], BANK[284]
INCBIN "images/nearest/resources.bin", 283 * $4000, $4000

SECTION "Bank285", ROMX[$4000], BANK[285]
INCBIN "images/nearest/resources.bin", 284 * $4000, $4000

SECTION "Bank286", ROMX[$4000], BANK[286]
INCBIN "images/nearest/resources.bin", 285 * $4000, $4000

SECTION "Bank287", ROMX[$4000], BANK[287]
INCBIN "images/nearest/resources.bin", 286 * $4000, $4000

SECTION "Bank288", ROMX[$4000], BANK[288]
INCBIN "images/nearest/resources.bin", 287 * $4000, $4000

SECTION "Bank289", ROMX[$4000], BANK[289]
INCBIN "images/nearest/resources.bin", 288 * $4000, $4000

SECTION "Bank290", ROMX[$4000], BANK[290]
INCBIN "images/nearest/resources.bin", 289 * $4000, $4000

SECTION "Bank291", ROMX[$4000], BANK[291]
INCBIN "images/nearest/resources.bin", 290 * $4000, $4000

SECTION "Bank292", ROMX[$4000], BANK[292]
INCBIN "images/nearest/resources.bin", 291 * $4000, $4000

SECTION "Bank293", ROMX[$4000], BANK[293]
INCBIN "images/nearest/resources.bin", 292 * $4000, $4000

SECTION "Bank294", ROMX[$4000], BANK[294]
INCBIN "images/nearest/resources.bin", 293 * $4000, $4000

SECTION "Bank295", ROMX[$4000], BANK[295]
INCBIN "images/nearest/resources.bin", 294 * $4000, $4000

SECTION "Bank296", ROMX[$4000], BANK[296]
INCBIN "images/nearest/resources.bin", 295 * $4000, $4000

SECTION "Bank297", ROMX[$4000], BANK[297]
INCBIN "images/nearest/resources.bin", 296 * $4000, $4000

SECTION "Bank298", ROMX[$4000], BANK[298]
INCBIN "images/nearest/resources.bin", 297 * $4000, $4000

SECTION "Bank299", ROMX[$4000], BANK[299]
INCBIN "images/nearest/resources.bin", 298 * $4000, $4000

SECTION "Bank300", ROMX[$4000], BANK[300]
INCBIN "images/nearest/resources.bin", 299 * $4000, $4000

SECTION "Bank301", ROMX[$4000], BANK[301]
INCBIN "images/nearest/resources.bin", 300 * $4000, $4000

SECTION "Bank302", ROMX[$4000], BANK[302]
INCBIN "images/nearest/resources.bin", 301 * $4000, $4000

SECTION "Bank303", ROMX[$4000], BANK[303]
INCBIN "images/nearest/resources.bin", 302 * $4000, $4000

SECTION "Bank304", ROMX[$4000], BANK[304]
INCBIN "images/nearest/resources.bin", 303 * $4000, $4000

SECTION "Bank305", ROMX[$4000], BANK[305]
INCBIN "images/nearest/resources.bin", 304 * $4000, $4000

SECTION "Bank306", ROMX[$4000], BANK[306]
INCBIN "images/nearest/resources.bin", 305 * $4000, $4000

SECTION "Bank307", ROMX[$4000], BANK[307]
INCBIN "images/nearest/resources.bin", 306 * $4000, $4000

SECTION "Bank308", ROMX[$4000], BANK[308]
INCBIN "images/nearest/resources.bin", 307 * $4000, $4000

SECTION "Bank309", ROMX[$4000], BANK[309]
INCBIN "images/nearest/resources.bin", 308 * $4000, $4000

SECTION "Bank310", ROMX[$4000], BANK[310]
INCBIN "images/nearest/resources.bin", 309 * $4000, $4000

SECTION "Bank311", ROMX[$4000], BANK[311]
INCBIN "images/nearest/resources.bin", 310 * $4000, $4000

SECTION "Bank312", ROMX[$4000], BANK[312]
INCBIN "images/nearest/resources.bin", 311 * $4000, $4000

SECTION "Bank313", ROMX[$4000], BANK[313]
INCBIN "images/nearest/resources.bin", 312 * $4000, $4000

SECTION "Bank314", ROMX[$4000], BANK[314]
INCBIN "images/nearest/resources.bin", 313 * $4000, $4000

SECTION "Bank315", ROMX[$4000], BANK[315]
INCBIN "images/nearest/resources.bin", 314 * $4000, $4000

SECTION "Bank316", ROMX[$4000], BANK[316]
INCBIN "images/nearest/resources.bin", 315 * $4000, $4000

SECTION "Bank317", ROMX[$4000], BANK[317]
INCBIN "images/nearest/resources.bin", 316 * $4000, $4000

SECTION "Bank318", ROMX[$4000], BANK[318]
INCBIN "images/nearest/resources.bin", 317 * $4000, $4000

SECTION "Bank319", ROMX[$4000], BANK[319]
INCBIN "images/nearest/resources.bin", 318 * $4000, $4000

SECTION "Bank320", ROMX[$4000], BANK[320]
INCBIN "images/nearest/resources.bin", 319 * $4000, $4000

SECTION "Bank321", ROMX[$4000], BANK[321]
INCBIN "images/nearest/resources.bin", 320 * $4000, $4000

SECTION "Bank322", ROMX[$4000], BANK[322]
INCBIN "images/nearest/resources.bin", 321 * $4000, $4000

SECTION "Bank323", ROMX[$4000], BANK[323]
INCBIN "images/nearest/resources.bin", 322 * $4000, $4000

SECTION "Bank324", ROMX[$4000], BANK[324]
INCBIN "images/nearest/resources.bin", 323 * $4000, $4000

SECTION "Bank325", ROMX[$4000], BANK[325]
INCBIN "images/nearest/resources.bin", 324 * $4000, $4000

SECTION "Bank326", ROMX[$4000], BANK[326]
INCBIN "images/nearest/resources.bin", 325 * $4000, $4000

SECTION "Bank327", ROMX[$4000], BANK[327]
INCBIN "images/nearest/resources.bin", 326 * $4000, $4000

SECTION "Bank328", ROMX[$4000], BANK[328]
INCBIN "images/nearest/resources.bin", 327 * $4000, $4000

SECTION "Bank329", ROMX[$4000], BANK[329]
INCBIN "images/nearest/resources.bin", 328 * $4000, $4000

SECTION "Bank330", ROMX[$4000], BANK[330]
INCBIN "images/nearest/resources.bin", 329 * $4000, $4000

SECTION "Bank331", ROMX[$4000], BANK[331]
INCBIN "images/nearest/resources.bin", 330 * $4000, $4000

SECTION "Bank332", ROMX[$4000], BANK[332]
INCBIN "images/nearest/resources.bin", 331 * $4000, $4000

SECTION "Bank333", ROMX[$4000], BANK[333]
INCBIN "images/nearest/resources.bin", 332 * $4000, $4000

SECTION "Bank334", ROMX[$4000], BANK[334]
INCBIN "images/nearest/resources.bin", 333 * $4000, $4000

SECTION "Bank335", ROMX[$4000], BANK[335]
INCBIN "images/nearest/resources.bin", 334 * $4000, $4000

SECTION "Bank336", ROMX[$4000], BANK[336]
INCBIN "images/nearest/resources.bin", 335 * $4000, $4000

SECTION "Bank337", ROMX[$4000], BANK[337]
INCBIN "images/nearest/resources.bin", 336 * $4000, $4000

SECTION "Bank338", ROMX[$4000], BANK[338]
INCBIN "images/nearest/resources.bin", 337 * $4000, $4000

SECTION "Bank339", ROMX[$4000], BANK[339]
INCBIN "images/nearest/resources.bin", 338 * $4000, $4000

SECTION "Bank340", ROMX[$4000], BANK[340]
INCBIN "images/nearest/resources.bin", 339 * $4000, $4000

SECTION "Bank341", ROMX[$4000], BANK[341]
INCBIN "images/nearest/resources.bin", 340 * $4000, $4000

SECTION "Bank342", ROMX[$4000], BANK[342]
INCBIN "images/nearest/resources.bin", 341 * $4000, $4000

SECTION "Bank343", ROMX[$4000], BANK[343]
INCBIN "images/nearest/resources.bin", 342 * $4000, $4000

SECTION "Bank344", ROMX[$4000], BANK[344]
INCBIN "images/nearest/resources.bin", 343 * $4000, $4000

SECTION "Bank345", ROMX[$4000], BANK[345]
INCBIN "images/nearest/resources.bin", 344 * $4000, $4000

SECTION "Bank346", ROMX[$4000], BANK[346]
INCBIN "images/nearest/resources.bin", 345 * $4000, $4000

SECTION "Bank347", ROMX[$4000], BANK[347]
INCBIN "images/nearest/resources.bin", 346 * $4000, $4000

SECTION "Bank348", ROMX[$4000], BANK[348]
INCBIN "images/nearest/resources.bin", 347 * $4000, $4000

SECTION "Bank349", ROMX[$4000], BANK[349]
INCBIN "images/nearest/resources.bin", 348 * $4000, $4000

SECTION "Bank350", ROMX[$4000], BANK[350]
INCBIN "images/nearest/resources.bin", 349 * $4000, $4000

SECTION "Bank351", ROMX[$4000], BANK[351]
INCBIN "images/nearest/resources.bin", 350 * $4000, $4000

SECTION "Bank352", ROMX[$4000], BANK[352]
INCBIN "images/nearest/resources.bin", 351 * $4000, $4000

SECTION "Bank353", ROMX[$4000], BANK[353]
INCBIN "images/nearest/resources.bin", 352 * $4000, $4000

SECTION "Bank354", ROMX[$4000], BANK[354]
INCBIN "images/nearest/resources.bin", 353 * $4000, $4000

SECTION "Bank355", ROMX[$4000], BANK[355]
INCBIN "images/nearest/resources.bin", 354 * $4000, $4000

SECTION "Bank356", ROMX[$4000], BANK[356]
INCBIN "images/nearest/resources.bin", 355 * $4000, $4000

SECTION "Bank357", ROMX[$4000], BANK[357]
INCBIN "images/nearest/resources.bin", 356 * $4000, $4000

SECTION "Bank358", ROMX[$4000], BANK[358]
INCBIN "images/nearest/resources.bin", 357 * $4000, $4000

SECTION "Bank359", ROMX[$4000], BANK[359]
INCBIN "images/nearest/resources.bin", 358 * $4000, $4000

SECTION "Bank360", ROMX[$4000], BANK[360]
INCBIN "images/nearest/resources.bin", 359 * $4000, $4000

SECTION "Bank361", ROMX[$4000], BANK[361]
INCBIN "images/nearest/resources.bin", 360 * $4000, $4000

SECTION "Bank362", ROMX[$4000], BANK[362]
INCBIN "images/nearest/resources.bin", 361 * $4000, $4000

SECTION "Bank363", ROMX[$4000], BANK[363]
INCBIN "images/nearest/resources.bin", 362 * $4000, $4000

SECTION "Bank364", ROMX[$4000], BANK[364]
INCBIN "images/nearest/resources.bin", 363 * $4000, $4000

SECTION "Bank365", ROMX[$4000], BANK[365]
INCBIN "images/nearest/resources.bin", 364 * $4000, $4000

SECTION "Bank366", ROMX[$4000], BANK[366]
INCBIN "images/nearest/resources.bin", 365 * $4000, $4000

SECTION "Bank367", ROMX[$4000], BANK[367]
INCBIN "images/nearest/resources.bin", 366 * $4000, $4000

SECTION "Bank368", ROMX[$4000], BANK[368]
INCBIN "images/nearest/resources.bin", 367 * $4000, $4000

SECTION "Bank369", ROMX[$4000], BANK[369]
INCBIN "images/nearest/resources.bin", 368 * $4000, $4000

SECTION "Bank370", ROMX[$4000], BANK[370]
INCBIN "images/nearest/resources.bin", 369 * $4000, $4000

SECTION "Bank371", ROMX[$4000], BANK[371]
INCBIN "images/nearest/resources.bin", 370 * $4000, $4000

SECTION "Bank372", ROMX[$4000], BANK[372]
INCBIN "images/nearest/resources.bin", 371 * $4000, $4000

SECTION "Bank373", ROMX[$4000], BANK[373]
INCBIN "images/nearest/resources.bin", 372 * $4000, $4000

SECTION "Bank374", ROMX[$4000], BANK[374]
INCBIN "images/nearest/resources.bin", 373 * $4000, $4000

SECTION "Bank375", ROMX[$4000], BANK[375]
INCBIN "images/nearest/resources.bin", 374 * $4000, $4000

SECTION "Bank376", ROMX[$4000], BANK[376]
INCBIN "images/nearest/resources.bin", 375 * $4000, $4000

SECTION "Bank377", ROMX[$4000], BANK[377]
INCBIN "images/nearest/resources.bin", 376 * $4000, $4000

SECTION "Bank378", ROMX[$4000], BANK[378]
INCBIN "images/nearest/resources.bin", 377 * $4000, $4000

SECTION "Bank379", ROMX[$4000], BANK[379]
INCBIN "images/nearest/resources.bin", 378 * $4000, $4000

SECTION "Bank380", ROMX[$4000], BANK[380]
INCBIN "images/nearest/resources.bin", 379 * $4000, $4000

SECTION "Bank381", ROMX[$4000], BANK[381]
INCBIN "images/nearest/resources.bin", 380 * $4000, $4000

SECTION "Bank382", ROMX[$4000], BANK[382]
INCBIN "images/nearest/resources.bin", 381 * $4000, $4000

SECTION "Bank383", ROMX[$4000], BANK[383]
INCBIN "images/nearest/resources.bin", 382 * $4000, $4000

SECTION "Bank384", ROMX[$4000], BANK[384]
INCBIN "images/nearest/resources.bin", 383 * $4000, $4000

SECTION "Bank385", ROMX[$4000], BANK[385]
INCBIN "images/nearest/resources.bin", 384 * $4000, $4000

SECTION "Bank386", ROMX[$4000], BANK[386]
INCBIN "images/nearest/resources.bin", 385 * $4000, $4000

SECTION "Bank387", ROMX[$4000], BANK[387]
INCBIN "images/nearest/resources.bin", 386 * $4000, $4000

SECTION "Bank388", ROMX[$4000], BANK[388]
INCBIN "images/nearest/resources.bin", 387 * $4000, $4000

SECTION "Bank389", ROMX[$4000], BANK[389]
INCBIN "images/nearest/resources.bin", 388 * $4000, $4000

SECTION "Bank390", ROMX[$4000], BANK[390]
INCBIN "images/nearest/resources.bin", 389 * $4000, $4000

SECTION "Bank391", ROMX[$4000], BANK[391]
INCBIN "images/nearest/resources.bin", 390 * $4000, $4000

SECTION "Bank392", ROMX[$4000], BANK[392]
INCBIN "images/nearest/resources.bin", 391 * $4000, $4000

SECTION "Bank393", ROMX[$4000], BANK[393]
INCBIN "images/nearest/resources.bin", 392 * $4000, $4000

SECTION "Bank394", ROMX[$4000], BANK[394]
INCBIN "images/nearest/resources.bin", 393 * $4000, $4000

SECTION "Bank395", ROMX[$4000], BANK[395]
INCBIN "images/nearest/resources.bin", 394 * $4000, $4000

SECTION "Bank396", ROMX[$4000], BANK[396]
INCBIN "images/nearest/resources.bin", 395 * $4000, $4000

SECTION "Bank397", ROMX[$4000], BANK[397]
INCBIN "images/nearest/resources.bin", 396 * $4000, $4000

SECTION "Bank398", ROMX[$4000], BANK[398]
INCBIN "images/nearest/resources.bin", 397 * $4000, $4000

SECTION "Bank399", ROMX[$4000], BANK[399]
INCBIN "images/nearest/resources.bin", 398 * $4000, $4000

SECTION "Bank400", ROMX[$4000], BANK[400]
INCBIN "images/nearest/resources.bin", 399 * $4000, $4000

SECTION "Bank401", ROMX[$4000], BANK[401]
INCBIN "images/nearest/resources.bin", 400 * $4000, $4000

SECTION "Bank402", ROMX[$4000], BANK[402]
INCBIN "images/nearest/resources.bin", 401 * $4000, $4000

SECTION "Bank403", ROMX[$4000], BANK[403]
INCBIN "images/nearest/resources.bin", 402 * $4000, $4000

SECTION "Bank404", ROMX[$4000], BANK[404]
INCBIN "images/nearest/resources.bin", 403 * $4000, $4000

SECTION "Bank405", ROMX[$4000], BANK[405]
INCBIN "images/nearest/resources.bin", 404 * $4000, $4000

SECTION "Bank406", ROMX[$4000], BANK[406]
INCBIN "images/nearest/resources.bin", 405 * $4000, $4000

SECTION "Bank407", ROMX[$4000], BANK[407]
INCBIN "images/nearest/resources.bin", 406 * $4000, $4000

SECTION "Bank408", ROMX[$4000], BANK[408]
INCBIN "images/nearest/resources.bin", 407 * $4000, $4000

SECTION "Bank409", ROMX[$4000], BANK[409]
INCBIN "images/nearest/resources.bin", 408 * $4000, $4000

SECTION "Bank410", ROMX[$4000], BANK[410]
INCBIN "images/nearest/resources.bin", 409 * $4000, $4000

SECTION "Bank411", ROMX[$4000], BANK[411]
INCBIN "images/nearest/resources.bin", 410 * $4000, $4000

SECTION "Bank412", ROMX[$4000], BANK[412]
INCBIN "images/nearest/resources.bin", 411 * $4000, $4000

SECTION "Bank413", ROMX[$4000], BANK[413]
INCBIN "images/nearest/resources.bin", 412 * $4000, $4000

SECTION "Bank414", ROMX[$4000], BANK[414]
INCBIN "images/nearest/resources.bin", 413 * $4000, $4000

SECTION "Bank415", ROMX[$4000], BANK[415]
INCBIN "images/nearest/resources.bin", 414 * $4000, $4000

SECTION "Bank416", ROMX[$4000], BANK[416]
INCBIN "images/nearest/resources.bin", 415 * $4000, $4000

SECTION "Bank417", ROMX[$4000], BANK[417]
INCBIN "images/nearest/resources.bin", 416 * $4000, $4000

SECTION "Bank418", ROMX[$4000], BANK[418]
INCBIN "images/nearest/resources.bin", 417 * $4000, $4000

SECTION "Bank419", ROMX[$4000], BANK[419]
INCBIN "images/nearest/resources.bin", 418 * $4000, $4000

SECTION "Bank420", ROMX[$4000], BANK[420]
INCBIN "images/nearest/resources.bin", 419 * $4000, $4000

SECTION "Bank421", ROMX[$4000], BANK[421]
INCBIN "images/nearest/resources.bin", 420 * $4000, $4000

SECTION "Bank422", ROMX[$4000], BANK[422]
INCBIN "images/nearest/resources.bin", 421 * $4000, $4000

SECTION "Bank423", ROMX[$4000], BANK[423]
INCBIN "images/nearest/resources.bin", 422 * $4000, $4000

SECTION "Bank424", ROMX[$4000], BANK[424]
INCBIN "images/nearest/resources.bin", 423 * $4000, $4000

SECTION "Bank425", ROMX[$4000], BANK[425]
INCBIN "images/nearest/resources.bin", 424 * $4000, $4000

SECTION "Bank426", ROMX[$4000], BANK[426]
INCBIN "images/nearest/resources.bin", 425 * $4000, $4000

SECTION "Bank427", ROMX[$4000], BANK[427]
INCBIN "images/nearest/resources.bin", 426 * $4000, $4000

SECTION "Bank428", ROMX[$4000], BANK[428]
INCBIN "images/nearest/resources.bin", 427 * $4000, $4000

SECTION "Bank429", ROMX[$4000], BANK[429]
INCBIN "images/nearest/resources.bin", 428 * $4000, $4000

SECTION "Bank430", ROMX[$4000], BANK[430]
INCBIN "images/nearest/resources.bin", 429 * $4000, $4000

SECTION "Bank431", ROMX[$4000], BANK[431]
INCBIN "images/nearest/resources.bin", 430 * $4000, $4000

SECTION "Bank432", ROMX[$4000], BANK[432]
INCBIN "images/nearest/resources.bin", 431 * $4000, $4000

SECTION "Bank433", ROMX[$4000], BANK[433]
INCBIN "images/nearest/resources.bin", 432 * $4000, $4000

SECTION "Bank434", ROMX[$4000], BANK[434]
INCBIN "images/nearest/resources.bin", 433 * $4000, $4000

SECTION "Bank435", ROMX[$4000], BANK[435]
INCBIN "images/nearest/resources.bin", 434 * $4000, $4000

SECTION "Bank436", ROMX[$4000], BANK[436]
INCBIN "images/nearest/resources.bin", 435 * $4000, $4000

SECTION "Bank437", ROMX[$4000], BANK[437]
INCBIN "images/nearest/resources.bin", 436 * $4000, $4000

SECTION "Bank438", ROMX[$4000], BANK[438]
INCBIN "images/nearest/resources.bin", 437 * $4000, $4000

SECTION "Bank439", ROMX[$4000], BANK[439]
INCBIN "images/nearest/resources.bin", 438 * $4000, $4000

SECTION "Bank440", ROMX[$4000], BANK[440]
INCBIN "images/nearest/resources.bin", 439 * $4000, $4000

SECTION "Bank441", ROMX[$4000], BANK[441]
INCBIN "images/nearest/resources.bin", 440 * $4000, $4000

SECTION "Bank442", ROMX[$4000], BANK[442]
INCBIN "images/nearest/resources.bin", 441 * $4000, $4000

SECTION "Bank443", ROMX[$4000], BANK[443]
INCBIN "images/nearest/resources.bin", 442 * $4000, $4000

SECTION "Bank444", ROMX[$4000], BANK[444]
INCBIN "images/nearest/resources.bin", 443 * $4000, $4000

SECTION "Bank445", ROMX[$4000], BANK[445]
INCBIN "images/nearest/resources.bin", 444 * $4000, $4000

SECTION "Bank446", ROMX[$4000], BANK[446]
INCBIN "images/nearest/resources.bin", 445 * $4000, $4000

SECTION "Bank447", ROMX[$4000], BANK[447]
INCBIN "images/nearest/resources.bin", 446 * $4000, $4000

SECTION "Bank448", ROMX[$4000], BANK[448]
INCBIN "images/nearest/resources.bin", 447 * $4000, $4000

SECTION "Bank449", ROMX[$4000], BANK[449]
INCBIN "images/nearest/resources.bin", 448 * $4000, $4000

SECTION "Bank450", ROMX[$4000], BANK[450]
INCBIN "images/nearest/resources.bin", 449 * $4000, $4000

SECTION "Bank451", ROMX[$4000], BANK[451]
INCBIN "images/nearest/resources.bin", 450 * $4000, $4000

SECTION "Bank452", ROMX[$4000], BANK[452]
INCBIN "images/nearest/resources.bin", 451 * $4000, $4000

SECTION "Bank453", ROMX[$4000], BANK[453]
INCBIN "images/nearest/resources.bin", 452 * $4000, $4000

SECTION "Bank454", ROMX[$4000], BANK[454]
INCBIN "images/nearest/resources.bin", 453 * $4000, $4000

SECTION "Bank455", ROMX[$4000], BANK[455]
INCBIN "images/nearest/resources.bin", 454 * $4000, $4000

SECTION "Bank456", ROMX[$4000], BANK[456]
INCBIN "images/nearest/resources.bin", 455 * $4000, $4000

SECTION "Bank457", ROMX[$4000], BANK[457]
INCBIN "images/nearest/resources.bin", 456 * $4000, $4000

SECTION "Bank458", ROMX[$4000], BANK[458]
INCBIN "images/nearest/resources.bin", 457 * $4000, $4000

SECTION "Bank459", ROMX[$4000], BANK[459]
INCBIN "images/nearest/resources.bin", 458 * $4000, $4000

SECTION "Bank460", ROMX[$4000], BANK[460]
INCBIN "images/nearest/resources.bin", 459 * $4000, $4000

SECTION "Bank461", ROMX[$4000], BANK[461]
INCBIN "images/nearest/resources.bin", 460 * $4000, $4000

SECTION "Bank462", ROMX[$4000], BANK[462]
INCBIN "images/nearest/resources.bin", 461 * $4000, $4000

SECTION "Bank463", ROMX[$4000], BANK[463]
INCBIN "images/nearest/resources.bin", 462 * $4000, $4000

SECTION "Bank464", ROMX[$4000], BANK[464]
INCBIN "images/nearest/resources.bin", 463 * $4000, $4000

SECTION "Bank465", ROMX[$4000], BANK[465]
INCBIN "images/nearest/resources.bin", 464 * $4000, $4000

SECTION "Bank466", ROMX[$4000], BANK[466]
INCBIN "images/nearest/resources.bin", 465 * $4000, $4000

SECTION "Bank467", ROMX[$4000], BANK[467]
INCBIN "images/nearest/resources.bin", 466 * $4000, $4000

SECTION "Bank468", ROMX[$4000], BANK[468]
INCBIN "images/nearest/resources.bin", 467 * $4000, $4000

SECTION "Bank469", ROMX[$4000], BANK[469]
INCBIN "images/nearest/resources.bin", 468 * $4000, $4000

SECTION "Bank470", ROMX[$4000], BANK[470]
INCBIN "images/nearest/resources.bin", 469 * $4000, $4000

SECTION "Bank471", ROMX[$4000], BANK[471]
INCBIN "images/nearest/resources.bin", 470 * $4000, $4000

SECTION "Bank472", ROMX[$4000], BANK[472]
INCBIN "images/nearest/resources.bin", 471 * $4000, $4000

SECTION "Bank473", ROMX[$4000], BANK[473]
INCBIN "images/nearest/resources.bin", 472 * $4000, $4000

SECTION "Bank474", ROMX[$4000], BANK[474]
INCBIN "images/nearest/resources.bin", 473 * $4000, $4000

SECTION "Bank475", ROMX[$4000], BANK[475]
INCBIN "images/nearest/resources.bin", 474 * $4000, $4000

SECTION "Bank476", ROMX[$4000], BANK[476]
INCBIN "images/nearest/resources.bin", 475 * $4000, $4000

SECTION "Bank477", ROMX[$4000], BANK[477]
INCBIN "images/nearest/resources.bin", 476 * $4000, $4000

SECTION "Bank478", ROMX[$4000], BANK[478]
INCBIN "images/nearest/resources.bin", 477 * $4000, 10235
